#This pipeline is to test the displayname message when we change the parameters
name: Run general script with approval

trigger: none

parameters:
  - name: script
    displayName: choose which script to run
    type: string
    default: test1
    values:
      - test1
      - test2
      - test3 
  - name: arguments
    displayName: the full arguments for the script to be executed
    type: string
    default: '-mail "user@example.com"'
    
jobs:
- job: Displayinstructions
  displayName: "DisplayInstructions"
  steps: 
  - script: |
      if [[ "${{ parameters.script }}" == 'test1' ]]; then
        arguments='-mail "user@example.com" -accountEnable $true'
      elif [[ "${{ parameters.script }}" == 'test2' ]]; then
        arguments='-mail "user@example.com" -status $false'
      elif [[ "${{ parameters.script }}" == 'test3' ]]; then
        arguments='-mail "user@example.com"'
      else
        arguments='-mail "user@example.com"'
      fi

      echo -e "\033[1;31mRunning script ${{ parameters.script }} with arguments: $arguments\033[0m"
    displayName: 'Display Instructions'

