# trigger job is used to which branch the build should trigger, here it triggers as soon as main branch updates. If we have a different branch to be triggered, please update accordingly.
trigger:
- main

# Build stage is used to create copy the files from system default to build artifactory, and publish them to azure pipelines.
stages:
# Build Stage
- stage: Build
  displayName: Build Stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
       vmImage: 'ubuntu-latest'
      steps:
      - bash: echo Contents present in system default directory; ls -R $(System.DefaultWorkingDirectory)  
      - bash: echo Contents present in Build Artifactory; ls -R $(Build.ArtifactStagingDirectory)
      
      - task: CopyFiles@2
        inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true
      - bash: echo Contents present in Build Artifactory; ls -R $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'