#This pipeline is to test the displayname message when we change the parameters
name: Run general script with approval

trigger: none

parameters:
  - name: script
    displayName: choose which script to run
    type: string
    default: test1
    values:
      - test1
      - test2
      - test3 
  - name: arguments
    displayName: the full arguments for the script to be executed
    type: string
    default: '-mail "user@example.com"'
    
jobs:
- job: Displayinstructions
  displayName: "DisplayInstructions"
  steps: 
  - script: |
      if [[ "${{ parameters.script }}" == 'test1' ]]; then
        echo -e "\033[1;31mRunning script test1 with arguments: ${{ parameters.arguments }}\033[0m"
      elif [[ "${{ parameters.script }}" == 'test2' ]]; then
        echo -e "\033[1;34mRunning script test2 with arguments: ${{ parameters.arguments }}\033[0m"
      elif [[ "${{ parameters.script }}" == 'test3' ]]; then
        echo -e "\033[1;32mRunning script test3 with arguments: ${{ parameters.arguments }}\033[0m"
      else
        echo -e "\033[1;33mUnknown script: ${{ parameters.script }}\033[0m"
      fi
    displayName: 'Display Instructions'

