name: Run general script with approval

trigger: none

parameters:
  - name: script
    displayName: choose which script to run
    type: string
    default: test1
    values:
      - test1
      - test2
      - test3 

jobs:
- job: Displayinstructions
  displayName: "Display Instructions"
  steps:
  - script: |
      if [[ "${{ parameters.script }}" == 'test1' ]]; then
        echo "##vso[task.setvariable variable=arguments]-mail \"user@example.com\" -accountEnable \$true"
      elif [[ "${{ parameters.script }}" == 'test2' ]]; then
        echo "##vso[task.setvariable variable=arguments]-mail \"user@example.com\" -status \$false"
      elif [[ "${{ parameters.script }}" == 'test3' ]]; then
        echo "##vso[task.setvariable variable=arguments]-mail \"user@example.com\""
      fi
    displayName: 'Set Arguments Based on Script'

  - script: |
      echo -e "\033[1;31mRunning script ${{ parameters.script }} with arguments: $(arguments)\033[0m"
    displayName: 'Display Instructions'
