#This pipeline is to test the displayname message when we change the parameters
name: Run general script with approval

trigger: none

parameters:
  - name: script
    displayName: choose which script to run
    type: string
    default: test1
    values:
      - test1
      - test2
      - test3 
      - test4
      - test5
      - test6
      - test7
  - name: arguments
    displayName: the full arguments for the script to be executed
    type: string
    default: '-mail "user@example.com": when we use ManageScript use -mail "user@example.com -enable $true/$false'
    

jobs:
- job: Displayinstructions
  displayName: "DisplayInstructions"
  steps:
  - template: set-arguments.yml
    parameters:
      script: ${{ parameters.script }}

  - script: |
      echo -e "\033[1;31mRunning script ${{ parameters.script }} with arguments: $(arguments)\033[0m"
    displayName: 'Display Instructions'


